export const countryData = [
  { name: 'Afghanistan', code: '+93', countryCode: 'AF' },
  { name: 'Albania', code: '+355', countryCode: 'AL' },
  { name: 'Algeria', code: '+213', countryCode: 'DZ' },
  { name: 'Andorra', code: '+376', countryCode: 'AD' },
  { name: 'Angola', code: '+244', countryCode: 'AO' },
  { name: 'Antigua and Barbuda', code: '+1-268', countryCode: 'AG' },
  { name: 'Argentina', code: '+54', countryCode: 'AR' },
  { name: 'Armenia', code: '+374', countryCode: 'AM' },
  { name: 'Australia', code: '+61', countryCode: 'AU' },
  { name: 'Austria', code: '+43', countryCode: 'AT' },
  { name: 'Azerbaijan', code: '+994', countryCode: 'AZ' },
  { name: 'Bahamas', code: '+1-242', countryCode: 'BS' },
  { name: 'Bahrain', code: '+973', countryCode: 'BH' },
  { name: 'Bangladesh', code: '+880', countryCode: 'BD' },
  { name: 'Barbados', code: '+1-246', countryCode: 'BB' },
  { name: 'Belarus', code: '+375', countryCode: 'BY' },
  { name: 'Belgium', code: '+32', countryCode: 'BE' },
  { name: 'Belize', code: '+501', countryCode: 'BZ' },
  { name: 'Benin', code: '+229', countryCode: 'BJ' },
  { name: 'Bhutan', code: '+975', countryCode: 'BT' },
  { name: 'Bolivia', code: '+591', countryCode: 'BO' },
  { name: 'Bosnia and Herzegovina', code: '+387', countryCode: 'BA' },
  { name: 'Botswana', code: '+267', countryCode: 'BW' },
  { name: 'Brazil', code: '+55', countryCode: 'BR' },
  { name: 'Brunei', code: '+673', countryCode: 'BN' },
  { name: 'Bulgaria', code: '+359', countryCode: 'BG' },
  { name: 'Burkina Faso', code: '+226', countryCode: 'BF' },
  { name: 'Burundi', code: '+257', countryCode: 'BI' },
  { name: 'Cabo Verde (Cape Verde)', code: '+238', countryCode: 'CV' },
  { name: 'Cambodia', code: '+855', countryCode: 'KH' },
  { name: 'Cameroon', code: '+237', countryCode: 'CM' },
  { name: 'Canada', code: '+1', countryCode: 'CA' },
  { name: 'Central African Republic', code: '+236', countryCode: 'CF' },
  { name: 'Chad', code: '+235', countryCode: 'TD' },
  { name: 'Chile', code: '+56', countryCode: 'CL' },
  { name: 'China', code: '+86', countryCode: 'CN' },
  { name: 'Colombia', code: '+57', countryCode: 'CO' },
  { name: 'Comoros', code: '+269', countryCode: 'KM' },
  { name: 'Congo, Democratic Republic of the', code: '+243', countryCode: 'CD' },
  { name: 'Congo, Republic of the', code: '+242', countryCode: 'CG' },
  { name: 'Costa Rica', code: '+506', countryCode: 'CR' },
  { name: 'Croatia', code: '+385', countryCode: 'HR' },
  { name: 'Cuba', code: '+53', countryCode: 'CU' },
  { name: 'Cyprus', code: '+357', countryCode: 'CY' },
  { name: 'Czech Republic', code: '+420', countryCode: 'CZ' },
  { name: 'Denmark', code: '+45', countryCode: 'DK' },
  { name: 'Djibouti', code: '+253', countryCode: 'DJ' },
  { name: 'Dominica', code: '+1-767', countryCode: 'DM' },
  { name: 'Dominican Republic', code: '+1-809', countryCode: 'DO' },
  { name: 'Dominican Republic', code: '+1-829', countryCode: 'DO' },
  { name: 'Dominican Republic', code: '+1-849', countryCode: 'DO' },
  { name: 'Ecuador', code: '+593', countryCode: 'EC' },
  { name: 'Egypt', code: '+20', countryCode: 'EG' },
  { name: 'El Salvador', code: '+503', countryCode: 'SV' },
  { name: 'Equatorial Guinea', code: '+240', countryCode: 'GQ' },
  { name: 'Eritrea', code: '+291', countryCode: 'ER' },
  { name: 'Estonia', code: '+372', countryCode: 'EE' },
  { name: 'Eswatini', code: '+268', countryCode: 'SZ' },
  { name: 'Ethiopia', code: '+251', countryCode: 'ET' },
  { name: 'Fiji', code: '+679', countryCode: 'FJ' },
  { name: 'Finland', code: '+358', countryCode: 'FI' },
  { name: 'France', code: '+33', countryCode: 'FR' },
  { name: 'Gabon', code: '+241', countryCode: 'GA' },
  { name: 'Gambia', code: '+220', countryCode: 'GM' },
  { name: 'Georgia', code: '+995', countryCode: 'GE' },
  { name: 'Germany', code: '+49', countryCode: 'DE' },
  { name: 'Ghana', code: '+233', countryCode: 'GH' },
  { name: 'Greece', code: '+30', countryCode: 'GR' },
  { name: 'Grenada', code: '+1-473', countryCode: 'GD' },
  { name: 'Guatemala', code: '+502', countryCode: 'GT' },
  { name: 'Guinea', code: '+224', countryCode: 'GN' },
  { name: 'Guinea-Bissau', code: '+245', countryCode: 'GW' },
  { name: 'Guyana', code: '+592', countryCode: 'GY' },
  { name: 'Haiti', code: '+509', countryCode: 'HT' },
  { name: 'Honduras', code: '+504', countryCode: 'HN' },
  { name: 'Hungary', code: '+36', countryCode: 'HU' },
  { name: 'Iceland', code: '+354', countryCode: 'IS' },
  { name: 'India', code: '+91', countryCode: 'IN' },
  { name: 'Indonesia', code: '+62', countryCode: 'ID' },
  { name: 'Iran', code: '+98', countryCode: 'IR' },
  { name: 'Iraq', code: '+964', countryCode: 'IQ' },
  { name: 'Ireland', code: '+353', countryCode: 'IE' },
  { name: 'Israel', code: '+972', countryCode: 'IL' },
  { name: 'Italy', code: '+39', countryCode: 'IT' },
  { name: 'Jamaica', code: '+1-876', countryCode: 'JM' },
  { name: 'Japan', code: '+81', countryCode: 'JP' },
  { name: 'Jordan', code: '+962', countryCode: 'JO' },
  { name: 'Kazakhstan', code: '+7', countryCode: 'KZ' },
  { name: 'Kenya', code: '+254', countryCode: 'KE' },
  { name: 'Kiribati', code: '+686', countryCode: 'KI' },
  { name: 'Korea, North', code: '+850', countryCode: 'KP' },
  { name: 'Korea, South', code: '+82', countryCode: 'KR' },
  { name: 'Kosovo', code: '+383', countryCode: 'XK' },
  { name: 'Kuwait', code: '+965', countryCode: 'KW' },
  { name: 'Kyrgyzstan', code: '+996', countryCode: 'KG' },
  { name: 'Laos', code: '+856', countryCode: 'LA' },
  { name: 'Latvia', code: '+371', countryCode: 'LV' },
  { name: 'Lebanon', code: '+961', countryCode: 'LB' },
  { name: 'Lesotho', code: '+266', countryCode: 'LS' },
  { name: 'Liberia', code: '+231', countryCode: 'LR' },
  { name: 'Libya', code: '+218', countryCode: 'LY' },
  { name: 'Liechtenstein', code: '+423', countryCode: 'LI' },
  { name: 'Lithuania', code: '+370', countryCode: 'LT' },
  { name: 'Luxembourg', code: '+352', countryCode: 'LU' },
  { name: 'Madagascar', code: '+261', countryCode: 'MG' },
  { name: 'Malawi', code: '+265', countryCode: 'MW' },
  { name: 'Malaysia', code: '+60', countryCode: 'MY' },
  { name: 'Maldives', code: '+960', countryCode: 'MV' },
  { name: 'Mali', code: '+223', countryCode: 'ML' },
  { name: 'Malta', code: '+356', countryCode: 'MT' },
  { name: 'Marshall Islands', code: '+692', countryCode: 'MH' },
  { name: 'Mauritania', code: '+222', countryCode: 'MR' },
  { name: 'Mauritius', code: '+230', countryCode: 'MU' },
  { name: 'Mexico', code: '+52', countryCode: 'MX' },
  { name: 'Micronesia', code: '+691', countryCode: 'FM' },
  { name: 'Moldova', code: '+373', countryCode: 'MD' },
  { name: 'Monaco', code: '+377', countryCode: 'MC' },
  { name: 'Mongolia', code: '+976', countryCode: 'MN' },
  { name: 'Montenegro', code: '+382', countryCode: 'ME' },
  { name: 'Morocco', code: '+212', countryCode: 'MA' },
  { name: 'Mozambique', code: '+258', countryCode: 'MZ' },
  { name: 'Myanmar (Burma)', code: '+95', countryCode: 'MM' },
  { name: 'Namibia', code: '+264', countryCode: 'NA' },
  { name: 'Nauru', code: '+674', countryCode: 'NR' },
  { name: 'Nepal', code: '+977', countryCode: 'NP' },
  { name: 'Netherlands', code: '+31', countryCode: 'NL' },
  { name: 'New Zealand', code: '+64', countryCode: 'NZ' },
  { name: 'Nicaragua', code: '+505', countryCode: 'NI' },
  { name: 'Niger', code: '+227', countryCode: 'NE' },
  { name: 'Nigeria', code: '+234', countryCode: 'NG' },
  { name: 'North Macedonia', code: '+389', countryCode: 'MK' },
  { name: 'Norway', code: '+47', countryCode: 'NO' },
  { name: 'Oman', code: '+968', countryCode: 'OM' },
  { name: 'Pakistan', code: '+92', countryCode: 'PK' },
  { name: 'Palau', code: '+680', countryCode: 'PW' },
  { name: 'Palestine', code: '+970', countryCode: 'PS' },
  { name: 'Panama', code: '+507', countryCode: 'PA' },
  { name: 'Papua New Guinea', code: '+675', countryCode: 'PG' },
  { name: 'Paraguay', code: '+595', countryCode: 'PY' },
  { name: 'Peru', code: '+51', countryCode: 'PE' },
  { name: 'Philippines', code: '+63', countryCode: 'PH' },
  { name: 'Poland', code: '+48', countryCode: 'PL' },
  { name: 'Portugal', code: '+351', countryCode: 'PT' },
  { name: 'Qatar', code: '+974', countryCode: 'QA' },
  { name: 'Romania', code: '+40', countryCode: 'RO' },
  { name: 'Russia', code: '+7', countryCode: 'RU' },
  { name: 'Rwanda', code: '+250', countryCode: 'RW' },
  { name: 'Saint Kitts and Nevis', code: '+1-869', countryCode: 'KN' },
  { name: 'Saint Lucia', code: '+1-758', countryCode: 'LC' },
  { name: 'Saint Vincent and the Grenadines', code: '+1-784', countryCode: 'VC' },
  { name: 'Samoa', code: '+685', countryCode: 'WS' },
  { name: 'San Marino', code: '+378', countryCode: 'SM' },
  { name: 'Sao Tome and Principe', code: '+239', countryCode: 'ST' },
  { name: 'Saudi Arabia', code: '+966', countryCode: 'SA' },
  { name: 'Senegal', code: '+221', countryCode: 'SN' },
  { name: 'Serbia', code: '+381', countryCode: 'RS' },
  { name: 'Seychelles', code: '+248', countryCode: 'SC' },
  { name: 'Sierra Leone', code: '+232', countryCode: 'SL' },
  { name: 'Singapore', code: '+65', countryCode: 'SG' },
  { name: 'Slovakia', code: '+421', countryCode: 'SK' },
  { name: 'Slovenia', code: '+386', countryCode: 'SI' },
  { name: 'Solomon Islands', code: '+677', countryCode: 'SB' },
  { name: 'Somalia', code: '+252', countryCode: 'SO' },
  { name: 'South Africa', code: '+27', countryCode: 'ZA' },
  { name: 'South Sudan', code: '+211', countryCode: 'SS' },
  { name: 'Spain', code: '+34', countryCode: 'ES' },
  { name: 'Sri Lanka', code: '+94', countryCode: 'LK' },
  { name: 'Sudan', code: '+249', countryCode: 'SD' },
  { name: 'Suriname', code: '+597', countryCode: 'SR' },
  { name: 'Sweden', code: '+46', countryCode: 'SE' },
  { name: 'Switzerland', code: '+41', countryCode: 'CH' },
  { name: 'Syria', code: '+963', countryCode: 'SY' },
  { name: 'Taiwan', code: '+886', countryCode: 'TW' },
  { name: 'Tajikistan', code: '+992', countryCode: 'TJ' },
  { name: 'Tanzania', code: '+255', countryCode: 'TZ' },
  { name: 'Thailand', code: '+66', countryCode: 'TH' },
  { name: 'Togo', code: '+228', countryCode: 'TG' },
  { name: 'Tonga', code: '+676', countryCode: 'TO' },
  { name: 'Trinidad and Tobago', code: '+1-868', countryCode: 'TT' },
  { name: 'Tunisia', code: '+216', countryCode: 'TN' },
  { name: 'Turkey', code: '+90', countryCode: 'TR' },
  { name: 'Turkmenistan', code: '+993', countryCode: 'TM' },
  { name: 'Tuvalu', code: '+688', countryCode: 'TV' },
  { name: 'Uganda', code: '+256', countryCode: 'UG' },
  { name: 'Ukraine', code: '+380', countryCode: 'UA' },
  { name: 'United Arab Emirates', code: '+971', countryCode: 'AE' },
  { name: 'United Kingdom', code: '+44', countryCode: 'GB' },
  { name: 'United States', code: '+1', countryCode: 'US' },
  { name: 'Uruguay', code: '+598', countryCode: 'UY' },
  { name: 'Uzbekistan', code: '+998', countryCode: 'UZ' },
  { name: 'Vanuatu', code: '+678', countryCode: 'VU' },
  { name: 'Vatican City', code: '+39', countryCode: 'VA' },
  { name: 'Venezuela', code: '+58', countryCode: 'VE' },
  { name: 'Vietnam', code: '+84', countryCode: 'VN' },
  { name: 'Yemen', code: '+967', countryCode: 'YE' },
  { name: 'Zambia', code: '+260', countryCode: 'ZM' },
  { name: 'Zimbabwe', code: '+263', countryCode: 'ZW' }
];
