export default {
    home: require('../assets/icons/home.png'),
    homeActive: require('../assets/icons/homeActive.png'),
    activity: require('../assets/icons/activity.png'),
    activityActive: require('../assets/icons/activityActive.png'),
    payment: require('../assets/icons/payment.png'),
    paymentActive: require('../assets/icons/activityActive.png'),
    team: require('../assets/icons/team.png'),
    teamActive: require('../assets/icons/teamActive.png'),
    leftArrow: require('../assets/icons/arrow-left.png'),
    buildingIcon:require('../assets/icons/buildings.png'),
    Call: require('../assets/icons/call.png'),
    sms: require('../assets/icons/sms.png'),
    start: require('../assets/icons/Star.png'),
    helpIcon: require('../assets/icons/tag-user.png'),
    channgePassword: require('../assets/icons/changePassword.png'),
    logout: require('../assets/icons/logout.png'),
    arrowRight:require('../assets/icons/rightArrow.png'),
    secourity: require('../assets/icons/security.png'),
    termsCondition: require('../assets/icons/termsCondition.png'),
    callIcon: require('../assets/icons/callIcon.png'),
    eyeIcon:require('../assets/icons/eye-slash.png'),
    keyIcon:require('../assets/icons/key.png'),
    crosssIcon:require('../assets/icons/crossIcon.png'),
    earning:require('../assets/icons/earning.png'),
    earningActive:require('../assets/icons/earningActive.png'),
    crewDummyOne:require('../assets/icons/crewDummyOe.png'),
    crewDummyTwo:require('../assets/icons/crewDummyTwo.png'),
    location:require('../assets/icons/location.png'),
    closeSquare:require('../assets/icons/closeSquare.png'),
    tickSquare:require('../assets/icons/tickSquare.png'),
    hammerIcon:require('../assets/icons/hammerIcon.png'),
    drillIcon:require('../assets/icons/drillIcon.png'),
};
